name: SoftendLib
main: kr.endsoft.softend.Main
version: 1.0.0
api-version: 1.20
author: E&D Soft
description: E&D Soft core library
website: http://endsoft.kr
commands:
  softend:
    permission: softend.admin
permissions:
  softend.admin:
    description: admin permission
    default: op